---
environment:
  NODE_ENV: production

deployment:
  tasks:
    - /opt/cpanel/ea-nodejs18/bin/npm install --omit=dev
    - echo "✅ Dependencies installed. Skipping build as it is already done locally."
    - /opt/cpanel/ea-nodejs18/bin/npm start
